server {
    listen 8080;
    server_name web-prod-01;
    access_log /var/log/nginx/juiceshop-access.log combined;
    error_log /var/log/nginx/juiceshop-error.log;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
