[WinEventLog://Security]
index = windows
sourcetype = WinEventLog:Security
disabled = false

[WinEventLog://System]
index = windows
sourcetype = WinEventLog:System
disabled = false

[WinEventLog://Application]
index = windows
sourcetype = WinEventLog:Application
disabled = false

[WinEventLog://Microsoft-Windows-PowerShell/Operational]
index = windows
sourcetype = WinEventLog:Microsoft-Windows-PowerShell/Operational
disabled = false
