[monitor:///var/log/syslog]
index = linux
sourcetype = syslog
disabled = false

[monitor:///var/log/auth.log]
index = linux
sourcetype = linux_secure
disabled = false

[monitor:///var/log/nginx/juiceshop-access.log]
index = webapp
sourcetype = access_combined
disabled = false

[monitor:///var/log/nginx/juiceshop-error.log]
index = webapp
sourcetype = nginx_error
disabled = false
